name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - 'gradle/wrapper/**'
  push:
    paths:
      - 'gradle/wrapper/**'

jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1.0.4
