name: benchmark-overhead tests
on:
  schedule:
    # 5am GMT
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: gh-pages
      - name: copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/benchmark-overhead/results/ benchmark-overhead/results/ && rm -rf gh-pages
      - name: run tests
        run: ./gradlew test
        working-directory: benchmark-overhead
      - name: commit updated results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          commit_message: update test result data
          file_pattern: benchmark-overhead/results